title: Dim Hoogeveen
logo: /assets/img/logo.png
description: The online resume (CV) of me (Dim Hoogeveen). I mainly created this to make myself more visible to everyone online.
show_downloads: false
google_analytics: UA-179304920-1
theme: jekyll-theme-minimal
