title: Dim Hoogeveen
description: The online resume (CV) of me (Dim Hoogeveen). I mainly created this to make myself more visible to everyone online.
url: "https://dimhoogeveen.com"
theme: jekyll-theme-minimal
google_analytics: UA-179304920-1

logo: /assets/img/logo_transparent.png
profile_picture: assets/img/DimProfilePictureWebsite270360.jpg
